import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { getPortfolioItems, getBlogItem } from "../../lib/data";
import Link from "next/link";
import { useRouter } from "next/router";

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: true,
  };
};

export const getStaticProps = async ({ params }) => {
  const blogItem = await getBlogItem(params.slug);
  return {
    props: {
      blogItem: blogItem.posts[0],
    },
  };
};

export default function Home({ blogItem }) {
  const router = useRouter();
  if (router.isFallback) {
    return <div>LOADING</div>;
  }
  console.log(blogItem);
  return (
    <div>
      <Head>
        <title>{blogItem.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{blogItem.title}</h1>
    </div>
  );
}
